name: send mail
on:
  push:
    branches:
      - main

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run : echo "Hello world"

    - name: Send email
      if: ${{ always() }}
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.google.com
        port: 465
        account: ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: muthu
        from: ${{secrets.MAIL_ADDRESS}}
        to: 125158038@sastra.ac.in
        subject: mail title.
        body: your messages.
          
        contentType: text/plain
        attachments: '[{"path":"README.md"}]'   