name: send mail
on:
  push:
    branches:
      - main

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run : echo "Hello world"

    - name: Send email
      if: ${{ always() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.ACCOUNT }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: mail title
        to: 125158038@sastra.ac.in
        from: ${{ secrets.MAIL_ADDRESS }}
        body: |
          Hello,
          
          your message here.
        content_type: text/plain
        attachments: README.md
  